#if !canImport(ObjectiveC)
import XCTest

extension STBTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__STBTests = [
        ("testImageLoading", testImageLoading)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(STBTests.__allTests__STBTests)
    ]
}
#endif
